site_name: rhdh-local
site_description: RHDH Local
site_author: user:user
docs_dir: docs
plugins:
  - techdocs-core
nav:
  - "Welcome To RHDH Local": index.md
  - "Getting Started With Red Hat Developer Hub (RHDH)":
    - "What Is Developer Hub And Why Is It Useful?": getting-started-rhdh/index.md
    - "Key Features & Benefits": getting-started-rhdh/highlights.md
    - "Navigating Around": getting-started-rhdh/navigation.md
    - "Using Search": getting-started-rhdh/search.md
    - "Understanding & Using the Software Catalog": getting-started-rhdh/software-catalog.md
    - "Understanding & Using TechDocs": getting-started-rhdh/techdocs.md
    - "Making Your TechDocs More Appealing": getting-started-rhdh/making-techdocs-appealing.md
    - "Understanding & Using The API Browser": getting-started-rhdh/apis.md
    - "Understanding & Using Templates": getting-started-rhdh/templates.md
    - "Writing Your Own Templates": getting-started-rhdh/templates-authoring.md
    - "Top 10 Tips For Better Software Templates": getting-started-rhdh/ten_template_tips.md
    # - "Understanding & Using Extensions (Plugins)": getting-started-rhdh/extensions.md
    - "Understanding & Using Developer Lightspeed": getting-started-rhdh/developer-lightspeed.md
  - "RHDH Local User Guide":
    - "Getting Started With RHDH Local": guides/getting-started.md
    - "Configuration": guides/configuration.md
    - "Loading Content": guides/loading-content.md
    - "Dynamic Plugin Management": guides/dynamic-plugins-management.md
    - "Local Plugin Development": guides/plugins-guide.md
    - "GitHub Authentication": guides/github-auth.md
    - "Container Image Guide": guides/container-image-guide.md
    - "Corporate Proxy Setup": guides/corporate-proxy-setup-sim.md
    - "PostgreSQL Guide": guides/postgresql-guide.md
    #- "Orchestrator": ../orchestrator/README.md
    - "Operating RHDH Local": guides/operating-rhdh-local.md
    - "Comparing Red Hat Developer Hub to CNCF Backstage": guides/comparison.md
    - "Getting Help & Contributing": guides/help-and-contrib.md
  - "References": references.md
